modified mkcpp to create multiple file

diff --git a/bin/mkcpp b/bin/mkcpp
--- a/bin/mkcpp
+++ b/bin/mkcpp
@@ -1,52 +1,53 @@
 #!/bin/sh
 
-if [ $# -ne 1 ]; then
-	echo "Error: input expected 1 argument (file name) to make cpp template."
+if [ $# -eq 0 ]; then
+	echo "Error: input expected arguments (file names) to make cpp template."
 	echo "Usage: mkcpp [file name]"
 	exit 1
 fi
 
-if [ -f "$1.cpp" ]; then
-	echo "Error: Duplicate file name"
-	exit 1
-fi
+for INDEX in $*
+do
+	if [ -f "${INDEX}.cpp" ]; then
+		echo "Error: Duplicate file name"
+		exit 1
+	fi
 
-cat << EOT  >> $1.cpp
-#define _USE_MATH_DEFINES
-#include <algorithm>
-#include <cstdio>
-#include <functional>
-#include <iostream>
-#include <cfloat>
-#include <climits>
-#include <cstring>
-#include <cmath>
-#include <map>
-#include <queue>
-#include <set>
-#include <sstream>
-#include <stack>
-#include <string>
-#include <time.h>
-#include <vector>
-using namespace std;
- 
-typedef long long ll;
-typedef unsigned long long ull;
-typedef pair<int, int> i_i;
-typedef pair<ll, int> ll_i;
-typedef pair<double, int> d_i;
-typedef pair<ll, ll> ll_ll;
-typedef pair<double, double> d_d;
-struct edge { int u, v; ll w; };
- 
-ll MOD = 1000000007;
-ll _MOD = 1000000009;
-double EPS = 1e-10;
+	cat <<-_EOT_ >> ${INDEX}.cpp
+	#define _USE_MATH_DEFINES
+	#include <algorithm>
+	#include <cstdio>
+	#include <functional>
+	#include <iostream>
+	#include <cfloat>
+	#include <climits>
+	#include <cstring>
+	#include <cmath>
+	#include <map>
+	#include <queue>
+	#include <set>
+	#include <sstream>
+	#include <stack>
+	#include <string>
+	#include <time.h>
+	#include <vector>
+	
+	typedef long long ll;
+	typedef unsigned long long ull;
+	typedef pair<int, int> i_i;
+	typedef pair<ll, int> ll_i;
+	typedef pair<double, int> d_i;
+	typedef pair<ll, ll> ll_ll;
+	typedef pair<double, double> d_d;
+	struct edge { int u, v; ll w; };
+	 
+	ll MOD = 1000000007;
+	ll _MOD = 1000000009;
+	double EPS = 1e-10;
 
-int main() {
+	int main() {
+		
+	}
+	_EOT_
 
-}
-EOT
-
-vim -c 34 $1.cpp
+done
